### ISSUE TITLE
Just wanted to clarify that node.js is not a **framework**

### ISSUE THREAD

**Issue by GmBodhi** [nikhils4/nikhils4.github.io#5]
![image](https://user-images.githubusercontent.com/71921036/127857662-b0d9a207-fda0-4b30-93fa-d0de087b8bab.png)
Node.js is a JS runtime environment, not a framework...

**Comment by nikhils4** [comment]
Working on the newer version of the website, will be pushing the changes soon, this is already fixed in the newer version. So I will close the issue as of now.

Thank you so much for taking your time and pointing this out.
